project_id = "jexcjraztxvhgxexozdd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.hash-password]
verify_jwt = false

[functions.clone-ifood-menu]
verify_jwt = false

[functions.clone-ifood-menu-v2]
verify_jwt = false

[functions.import-menu-from-screenshot]
verify_jwt = false